/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccademyMain: typeof import('./src/components/accademy/AccademyMain.vue')['default']
    CardMain: typeof import('./src/components/news/CardMain.vue')['default']
    GameMain: typeof import('./src/components/accademy/GameMain.vue')['default']
    Menu: typeof import('./src/components/menu/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
